spring.application.name=SpringBootProject
logging.level.org.springframework=ERROR
server.port=8084
spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

spring.datasource.url=jdbc:postgresql://localhost:5432/spring-db
spring.datasource.username=rajesh
spring.datasource.password=rajesh

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Optional: Keep this if you want to see pretty-printed SQL in your console
spring.jpa.properties.hibernate.format_sql=true


spring.h2.console.settings.web-allow-others=true
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-exception=true


# Failure rate threshold: If 50% of requests fail, open the circuit
resilience4j.circuitbreaker.instances.userServiceBreaker.failure-rate-threshold=50
# Minimum number of calls before calculating failure rate
resilience4j.circuitbreaker.instances.userServiceBreaker.minimum-number-of-calls=5
# How long to wait before trying the service again (in seconds)
resilience4j.circuitbreaker.instances.userServiceBreaker.wait-duration-in-open-state=10s
# Allow Swagger/Health to see the status
management.health.circuitbreakers.enabled=true


resilience4j.ratelimiter.enabled=true
# Define a limit: 3 requests every 10 seconds
resilience4j.ratelimiter.instances.userApiLimiter.limit-for-period=1
resilience4j.ratelimiter.instances.userApiLimiter.limit-refresh-period=30s
resilience4j.ratelimiter.instances.userApiLimiter.timeout-duration=0s


# kafka configurations
spring.kafka.bootstrap-servers=localhost:9092

#kafka streams
spring.kafka.streams.application-id=my-streams-app

# Set the commit interval to 100 milliseconds (0.1 seconds)
spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms=10000
spring.cloud.stream.kafka.streams.binder.configuration.cache.max.bytes.buffering=900

spring.cloud.stream.kafka.streams.binder.configuration.processing.guarantee=exactly_once_v2

